test-3.5:
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - virtualenv --clear -p python3.5 .
  - source bin/activate
  - pip install -e .
  - cd tests
  - python -m unittest discover

test-2.7:
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - virtualenv --clear -p python2.7 .
  - source bin/activate
  - pip install -e .
  - cd tests
  - python -m unittest discover
