stages:
  - build
  - test

build-3.5:
  stage: build
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - virtualenv --clear -p python3.5 ./venv3
  - source venv3/bin/activate
  - python setup.py bdist_wheel --dist-dir dist3

build-2.7:
  stage: build
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - virtualenv --clear -p python2.7 ./venv2
  - source venv2/bin/activate
  - python setup.py bdist_wheel --dist-dir dist2

test-3.5:
  stage: test
  tags:
    - Linux
  script:
  - source venv3/bin/activate
  - pip install dist3/*.whl
  - cd tests
  - python -m unittest discover

test-2.7:
  stage: test
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - source venv2/bin/activate
  - pip install dist2/*.whl
  - cd tests
  - python -m unittest discover
