stages:
  - build
  - test
  - deploy

build-3.5-linux-macos:
  stage:
    build
  tags:
    - Linux
    - Apple
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - export PATH=/opt/local/bin:$PATH
    - virtualenv --clear -p python3.5 .
    - source bin/activate
    - python setup.py bdist_wheel --dist-dir dist3
  artifacts:
    paths:
      - dist3/

build-2.7-linux-macos:
  stage:
    build
  tags:
    - Linux
    - Apple
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - export PATH=/opt/local/bin:$PATH
    - virtualenv --clear -p python2.7 .
    - source bin/activate
    - python setup.py bdist_wheel --dist-dir dist2
  artifacts:
    paths:
      - dist2/

test-3.5-linux-macos:
  stage:
    test
  tags:
    - Linux
    - Apple
  dependencies:
    - build-3.5-linux-macos
  script:
    - export PATH=/opt/local/bin:$PATH
    - virtualenv --clear -p python3.5 .
    - source bin/activate
    - pip install dist3/*.whl
    - cd tests
    - python -m unittest discover

test-2.7-linux-macos:
  stage:
    test
  tags:
    - Linux
    - Apple
  dependencies:
    - build-2.7-linux-macos
  script:
    - export PATH=/opt/local/bin:$PATH
    - virtualenv --clear -p python2.7 .
    - source bin/activate
    - pip install dist2/*.whl
    - cd tests
    - python -m unittest discover

deploy-3.5-linux-macos:
  stage:
    deploy
  tags:
    - Linux
    - Apple
  dependencies:
    - build-3.5-linux-macos
  script:
    - mkdir release
    - cp dist3/*.whl release
  artifacts:
    paths:
      - release/*.whl

deploy-2.7-linux-macos:
  stage:
    deploy
  tags:
    - Linux
    - Apple
  dependencies:
    - build-2.7-linux-macos
  script:
    - mkdir release
    - cp dist2/*.whl release
  artifacts:
    paths:
      - release/*.whl
