stages:
  - build
  - test
  - deploy

build-3.5:
  stage:
    build
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - virtualenv --clear -p python3.5 ./venv3
    - source ./venv3/bin/activate
    - python setup.py bdist_wheel --dist-dir dist3
    - pip install dist3/*.whl
  artifacts:
    paths:
      - dist3/
      - venv3/

build-2.7:
  stage:
    build
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - virtualenv --clear -p python2.7 ./venv2
    - source ./venv2/bin/activate
    - python setup.py bdist_wheel --dist-dir dist2
    - pip install dist2/*.whl
  artifacts:
    paths:
      - dist2/
      - venv2/

test-3.5:
  stage:
    test
  tags:
    - Linux
  dependencies:
    - build-3.5
  script:
    - source ./venv3/bin/activate
    - cd tests
    - python -m unittest discover

test-2.7:
  stage:
    test
  tags:
    - Linux
  dependencies:
    - build-2.7
  script:
    - source ./venv2/bin/activate
    - cd tests
    - python -m unittest discover

deploy-3.5:
  stage:
    deploy
  tags:
    - Linux
  dependencies:
    - build-3.5
  script:
    - mkdir release
    - cp dist3/*.whl release
  artifacts:
    paths:
      - release/*.whl

deploy-2.7:
  stage:
    deploy
  tags:
    - Linux
  dependencies:
    - build-2.7
  script:
    - mkdir release
    - cp dist2/*.whl release
  artifacts:
    paths:
      - release/*.whl
