test-3.5:
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - virtualenv --clear -p python3.5 .
  - source bin/activate
  - python setup.py bdist_wheel --dist-dir dist3
  - pip install dist3/*.whl
  - cd tests
  - python -m unittest discover

test-2.7:
  tags:
    - Linux
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - virtualenv --clear -p python2.7 .
  - source bin/activate
  - python setup.py bdist_wheel --dist-dir dist2
  - pip install dist2/*.whl
  - cd tests
  - python -m unittest discover
